### ISSUE TITLE
I couldn’t find the folder ‘twitter_json’. Can you offer me a link to download it? Thanks very much.

### ISSUE THREAD

**Issue by mingmingDiii** [Wario7/RumorDetectionRNN#1]
I couldn’t find the folder ‘twitter_json’. Can you offer me a link to download it? Thanks very much.

**Comment by pizazzche** [comment]
> I couldn’t find the folder ‘twitter_json’. Can you offer me a link to download it? Thanks very much.
Have you got the folder 'twitter_json' ???
