### ISSUE TITLE
How can i add new rumor file

### ISSUE THREAD

**Issue by jwzxgy2007** [Wario7/RumorDetectionRNN#2]
Hello Wario7, your project is really cool! I run the RumorRNN.py and get the result, and now I want to add my own rumor files to training, but i don't have the rumor/twitter_json/Airfrance.json file. I don't know the object in these json files, could you plase provide some rumor json files or tell me the form of these json files, thank you !

**Comment by abalhomaid** [comment]
Hello jwzxgy2007, 

Thank you for your interest. Please find below Google drive link for twitter_json folder,  make sure to unzip it below rumor folder :)

https://drive.google.com/open?id=1ItV93gXuIm0QG1is-mzGWPYSzjxgIY7Z

**Comment by jwzxgy2007** [comment]
@Wario7 Thank you! I'll download it
